### PR TITLE
Added next steps for ease of accessibility

### PR DESCRIPTION
**Pull request by AbhiSaphire**

### CODE REVIEW

**Comment by ahtee** [comment]
https://github.com/Microsoft/frontend-bootcamp/pull/74#pullrequestreview-210403119

**Comment by ahtee** [comment]
https://github.com/Microsoft/frontend-bootcamp/pull/74#discussion_r262272827

**Comment by ahtee** [comment]
Please close the other PR (#74) if this is to replace it.

**Comment by micahgodbolt** [comment]
after a number of updates, there are tons of conflicts here. can you clean them up?

**Comment by micahgodbolt** [comment]
Sorry we went and hacked on all the readme files. In general, we aren't using rendered readmes to navigate, so this probably isn't 100% necessary. If you want to take another stab, I don't mind.

**Pull request closed without merging**
