### PR TITLE
Folders hierarchy fix

### PR DESCRIPTION
**Pull request by riccardoerra**
Was `components/src/TodoHeader.tsx`. Based on previous and successive examples that's incorrect.

### CODE REVIEW

**Comment by goldloops** [comment]
Duplicate of #[Sarkozy](url)

**Comment by dannyjr894** [comment]
No name how about a number

**Comment by dannyjr894** [comment]
U kw I'm new here I'm not to computer savvy and y u call n me eveldee is the person label n me 0

**Comment by dannyjr894** [comment]
U kw I'm new here I'm not to computer savvy and y u call n me eveldee is the person label n me 0 how do I delete this account

**Comment by dannyjr894** [comment]
Delete my account

**Comment by dannyjr894** [comment]
How many times can I ask to delete this account

**Pull request merged**
